import { Open_Sans } from "next/font/google";
import "./styles/globals.css";
import Footer from "@/components/Ui/Footer";
import Providers from "@/lib/Providers";

const opensans = Open_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body className={opensans.className}>
          {children}
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
